export const listEthnicity = [
  "African American",
  "Alaska Native",
  "American Indian",
  "Asian",
  "Black",
  "Hispanic",
  "Latino",
  "Native Hawaiian",
  "Pacific Islander",
  "White",
]

export const listLanguages = [
  "Afrikaans",
  "Amharic",
  "Arabic",
  "Bengali",
  "Bulgarian",
  "Catalan",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Finnish",
  "French",
  "Galician",
  "German",
  "Greek",
  "Hausa",
  "Hindi",
  "Hungarian",
  "Igbo",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Malay",
  "Norwegian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Thai",
  "Turkish",
  "Urdu",
  "Vietnamese",
  "Yoruba",
  "Zulu",
]

export const listInterests = [
  "Arts & Culture",
  "Careers",
  "Business & Finance",
  "Disability Advocacy",
  "Entertainment",
  "Fashion & Beauty",
  "Fitness",
  "Food",
  "Gaming",
  "Home & Family",
  "Married",
  "Military",
  "Movies & TV",
  "Music",
  "News",
  "NFTs",
]

export const listWhichBestDescribesYou = [
  "Professional Athlete",
  "Student-Athlete",
  "Retired Athlete",
  "Coach",
  "Staff",
  "Trainer",
  "Broadcaster",
  "Sports Exec",
]
export const listGenderIdentities = [
  "Female",
  "Male",
  "Non-Binary",
  "Other Gender",
]

export const listSports = [
  "Archery",
  "Badminton",
  "Baseball",
  "Basketball",
  "Climbing",
  "Fencing",
  "Golf",
  "Hockey",
  "Soccer",
  "Volleyball",
]

export const listCurrentTeam = [
  "AC Milan (Serie A)",
  "AC Milan (Serie A)",
  "Arizona Cardinals (NFL)",
  "Arsenal FC (Premier League)",
  "AS Roma (Serie A)",
  "Baltimore Ravens (NFL)",
  "Bayern Munich (Bundesliga)",
  "Boston Red Sox (MLB)",
  "Chicago Bulls (NBA)",
  "Chicago Cubs (MLB)",
  "Chelsea FC (Premier League)",
  "Cleveland Cavaliers (NBA)",
  "Dallas Cowboys (NFL)",
  "Denver Broncos (NFL)",
  "FC Barcelona (La Liga)",
  "Golden State Warriors (NBA)",
  "Green Bay Packers (NFL)",
  "Green Bay Packers (NFL)",
  "Houston Rockets (NBA)",
  "Inter Milan (Serie A)",
  "Kansas City Chiefs (NFL)",
  "Liverpool FC (Premier League)",
  "Los Angeles Dodgers (MLB)",
  "Los Angeles Lakers (NBA)",
  "Los Angeles Rams (NFL)",
  "Manchester City FC (Premier League)",
  "Manchester City FC (Premier League)",
  "Manchester United FC (Premier League)",
  "Miami Dolphins (NFL)",
  "Miami Heat (NBA)",
  "Minnesota Vikings (NFL)",
  "New England Patriots (NFL)",
  "New England Patriots (NFL)",
  "New Orleans Saints (NFL)",
  "New York Giants (NFL)",
  "New York Knicks (NBA)",
  "New York Lakers (NBA)",
  "New York Mets (MLB)",
  "New York Yankees (MLB)",
  "Philadelphia Eagles (NFL)",
  "Pittsburgh Steelers (NFL)",
  "Portland Trail Blazers (NBA)",
  "Real Madrid Baloncesto (Liga ACB)",
  "Real Madrid CF (La Liga)",
  "San Antonio Spurs (NBA)",
  "San Francisco 49ers (NFL)",
  "Seattle Seahawks (NFL)",
  "Seattle Sounders FC (MLS)",
  "Tottenham Hotspur FC (Premier League)",
  "Toronto Blue Jays (MLB)",
  "Toronto Raptors (NBA)",
  "Utah Jazz (NBA)",
]
