export const listAthleticAccolades = [
  "Olympic Gold Medal",
  "World Championship Title",
  "Super Bowl MVP",
  "MVP (Most Valuable Player)",
  "Heisman Trophy",
  "NBA Finals MVP",
  "Triple Crown Winner (Horse Racing)",
  "Golden Boot Award (Soccer)",
  "Grand Slam (Tennis)",
  "Green Jacket (The Masters Golf Tournament)",
  "Stanley Cup Champion",
  "World Series Champion",
  "Tour de France Yellow Jersey",
  "UEFA Champions League Winner",
  "All-Star Selection",
  "Indy 500 Winner",
  "Gold Gloves (Boxing)",
  "PGA Tour Player of the Year",
  "Silver Slugger Award (Baseball)",
  "NFL Defensive Player of the Year",
]

export const listPreviousTeams = [
  "Los Angeles Lakers",
  "Golden State Warriors",
  "Chicago Bulls",
  "Boston Celtics",
  "Miami Heat",
  "San Antonio Spurs",
  "Toronto Raptors",
  "Philadelphia 76ers",
  "Houston Rockets",
  "Milwaukee Bucks",
  "Dallas Mavericks",
  "Denver Nuggets",
  "Portland Trail Blazers",
  "New York Knicks",
  "Indiana Pacers",
  "Utah Jazz",
  "Brooklyn Nets",
  "Phoenix Suns",
  "Oklahoma City Thunder",
  "Atlanta Hawks",
  "Detroit Pistons",
  "Minnesota Timberwolves",
  "New Orleans Pelicans",
  "Cleveland Cavaliers",
  "Orlando Magic",
  "Sacramento Kings",
  "Washington Wizards",
  "Charlotte Hornets",
  "Memphis Grizzlies",
  "Los Angeles Clippers",
  "Seattle SuperSonics",
  "Vancouver Grizzlies",
  "New Jersey Nets",
  "Charlotte Bobcats",
  "San Diego Clippers",
  "Kansas City Kings",
  "Buffalo Braves",
  "St. Louis Hawks",
  "Syracuse Nationals",
  "Fort Wayne Pistons",
  "Rochester Royals",
  "Indianapolis Jets",
  "Cincinnati Royals",
  "Chicago Stags",
  "Washington Capitols",
  "Providence Steamrollers",
  "Toronto Huskies",
  "Pittsburgh Ironmen",
  "Indianapolis Olympians",
  "Waterloo Hawks",
  "St. Louis Bombers",
  "Chicago American Gears",
  "Denver Nuggets (1948)",
  "Sheboygan Red Skins",
  "Anderson Packers",
  "Tri-Cities Blackhawks",
  "Baltimore Bullets",
  "Chicago Packers",
  "Milwaukee Hawks",
  "Kansas City-Omaha Kings",
  "New Orleans / Utah Jazz",
  "San Diego / Houston Rockets",
]

export const listDiscipline = [
  "Alpine Skiing",
  "Artistic Gymnastics",
  "Beach Volleyball",
  "BMX Freestyle",
  "Cross-Country Skiing",
  "Cyclocross",
  "Diving",
  "Figure Skating",
  "Gymnastics (Rhythmic)",
  "Ice Hockey",
  "Martial Arts (Judo, Karate, Taekwondo)",
  "Mountain Biking",
  "Rhythmic Gymnastics",
  "Ski Jumping",
  "Snowboarding (Halfpipe, Slopestyle)",
  "Synchronized Swimming",
  "Trampoline Gymnastics",
  "Triathlon",
  "Volleyball (Indoor)",
  "Water Polo",
  "Wrestling (Freestyle, Greco-Roman)",
  "Archery",
  "Badminton",
  "Baseball",
  "Basketball",
  "Boxing",
  "Canoeing (Sprint, Slalom)",
  "Curling",
  "Equestrian (Dressage, Eventing, Jumping)",
  "Fencing",
  "Field Hockey",
  "Football (Soccer)",
  "Golf",
  "Handball",
  "Lacrosse",
  "Modern Pentathlon",
  "Rowing",
  "Rugby (Sevens, Union)",
  "Sailing",
  "Shooting",
  "Skateboarding",
  "Speed Skating",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "Tennis",
  "Track and Field (Athletics)",
  "Weightlifting",
  "Wrestling (Freestyle, Greco-Roman)",
]

export const listExperience = [
  "Alumni",
  "College",
  "Freshmen",
  "High School",
  "Junior",
  "Olympian",
  "Olympic Hopeful",
  "Paralympian",
  "Paralympic Hopeful",
  "Senior",
  "Sophomore",
]

export const listLeagueConferences = [
  "NSL",
  "GSL",
  "IBA",
  "WRC",
  "PTA",
  "GCL",
  "MBF",
  "NHA",
  "PGT",
  "WSL",
  "IVA",
  "GEC",
  "NMAL",
  "PARS",
  "WCF",
  "GTTL",
  "NLA",
  "PTFL",
  "WGC",
  "ISS",
  "GAL",
  "NESL",
  "PST",
  "WBSA",
  "IBC",
  "GJF",
  "NKL",
  "PFA",
  "WTA",
  "GPL",
  "NSSS",
  "PRC",
  "WISA",
  "IWF",
  "GWPL",
  "NDA",
  "PBT",
  "WEC",
  "ICKF",
  "GRDL",
  "NUFL",
  "PCS",
  "WTA",
  "ISC",
  "GHML",
  "NOA",
  "PCF",
  "WSWA",
  "International Tech Summit",
  "Global Marketing Symposium",
  "World Education Expo",
  "Medical Innovation Conference",
  "Environmental Sustainability Forum",
  "Digital Transformation Congress",
  "Artificial Intelligence Symposium",
  "Business Leadership Summit",
  "Future of Healthcare Conference",
  "Renewable Energy Expo",
  "Space Exploration Congress",
  "Innovation in Finance Forum",
  "Human Rights Symposium",
  "Economic Development Summit",
  "Green Technology Conference",
  "Fashion and Design Expo",
  "Cybersecurity Conference",
  "Food and Beverage Symposium",
  "Sustainable Agriculture Forum",
  "International Film Festival",
  "Travel and Tourism Summit",
  "Global Music Conference",
  "Health and Wellness Expo",
  "Renewable Energy Congress",
  "Education Technology Forum",
  "International Literature Conference",
  "Entrepreneurship Expo",
  "Global Sports Summit",
  "Tech Startups Conference",
  "Science and Research Symposium",
  "Blockchain and Cryptocurrency Expo",
  "Art and Culture Festival",
  "Aerospace and Aviation Conference",
  "Blockchain and Cryptocurrency Expo",
  "Art and Culture Festival",
  "Aerospace and Aviation Conference",
  "Global Climate Change Forum",
  "Leadership Development Seminar",
  "International Trade Expo",
  "Psychology and Mental Health Conference",
  "Robotics and Automation Summit",
  "Future of Transportation Symposium",
  "Fashion Technology Conference",
  "Space Technology Expo",
  "Global Food and Agriculture Forum",
  "International Renewable Resources Congress",
  "Blockchain and Decentralized Finance Summit",
  "Bioinformatics and Genomics Symposium",
  "Green Energy Technology Conference",
]

export const listTeams = [
  "Los Angeles Lakers",
  "Golden State Warriors",
  "Chicago Bulls",
  "Boston Celtics",
  "Miami Heat",
  "San Antonio Spurs",
  "Toronto Raptors",
  "Philadelphia 76ers",
  "Houston Rockets",
  "Milwaukee Bucks",
  "Dallas Mavericks",
  "Denver Nuggets",
  "Portland Trail Blazers",
  "New York Knicks",
  "Indiana Pacers",
  "Utah Jazz",
  "Brooklyn Nets",
  "Phoenix Suns",
  "Oklahoma City Thunder",
  "Atlanta Hawks",
  "Detroit Pistons",
  "Minnesota Timberwolves",
  "New Orleans Pelicans",
  "Cleveland Cavaliers",
  "Orlando Magic",
  "Sacramento Kings",
  "Washington Wizards",
  "Charlotte Hornets",
  "Memphis Grizzlies",
  "Los Angeles Clippers",
  "Seattle SuperSonics",
  "Vancouver Grizzlies",
  "New Jersey Nets",
  "Charlotte Bobcats",
  "San Diego Clippers",
  "Kansas City Kings",
  "Buffalo Braves",
  "St. Louis Hawks",
  "Syracuse Nationals",
  "Fort Wayne Pistons",
  "Rochester Royals",
  "Indianapolis Jets",
  "Cincinnati Royals",
  "Chicago Stags",
  "Washington Capitols",
  "Providence Steamrollers",
  "Toronto Huskies",
  "Pittsburgh Ironmen",
  "Indianapolis Olympians",
  "Waterloo Hawks",
  "St. Louis Bombers",
  "Chicago American Gears",
  "Denver Nuggets (1948)",
  "Sheboygan Red Skins",
  "Anderson Packers",
  "Tri-Cities Blackhawks",
  "Baltimore Bullets",
  "Chicago Packers",
  "Milwaukee Hawks",
  "Kansas City-Omaha Kings",
  "New Orleans / Utah Jazz",
  "San Diego / Houston Rockets",
]


export const listPosition = [
  "All Around",
  "Point Guard",
  "Shooting Guard",
  "Small Forward",
  "Power Forward",
  "Center",
]

export const listEthnicity = [
  "African American",
  "Alaska Native",
  "American Indian",
  "Asian",
  "Black",
  "Hispanic",
  "Latino",
  "Native Hawaiian",
  "Pacific Islander",
  "White",
]

export const listLanguages = [
  "Afrikaans",
  "Amharic",
  "Arabic",
  "Bengali",
  "Bulgarian",
  "Catalan",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Finnish",
  "French",
  "Galician",
  "German",
  "Greek",
  "Hausa",
  "Hindi",
  "Hungarian",
  "Igbo",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Malay",
  "Norwegian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Thai",
  "Turkish",
  "Urdu",
  "Vietnamese",
  "Yoruba",
  "Zulu",
]

export const listInterests = [
  "Arts & Culture",
  "Careers",
  "Business & Finance",
  "Disability Advocacy",
  "Entertainment",
  "Fashion & Beauty",
  "Fitness",
  "Food",
  "Gaming",
  "Home & Family",
  "Married",
  "Military",
  "Movies & TV",
  "Music",
  "News",
  "NFTs",
]

export const listWhichBestDescribesYou = [
  "Professional Athlete",
  "Student-Athlete",
  "Retired Athlete",
  "Coach",
  "Staff",
  "Trainer",
  "Broadcaster",
  "Sports Exec",
]
export const listGenderIdentities = [
  "Female",
  "Male",
  "Non-Binary",
  "Other Gender",
]

export const listSports = [
  "Archery",
  "Badminton",
  "Baseball",
  "Basketball",
  "Climbing",
  "Fencing",
  "Golf",
  "Hockey",
  "Soccer",
  "Volleyball",
]

export const listCurrentTeam = [
  "AC Milan (Serie A)",
  "AC Milan (Serie A)",
  "Arizona Cardinals (NFL)",
  "Arsenal FC (Premier League)",
  "AS Roma (Serie A)",
  "Baltimore Ravens (NFL)",
  "Bayern Munich (Bundesliga)",
  "Boston Red Sox (MLB)",
  "Chicago Bulls (NBA)",
  "Chicago Cubs (MLB)",
  "Chelsea FC (Premier League)",
  "Cleveland Cavaliers (NBA)",
  "Dallas Cowboys (NFL)",
  "Denver Broncos (NFL)",
  "FC Barcelona (La Liga)",
  "Golden State Warriors (NBA)",
  "Green Bay Packers (NFL)",
  "Green Bay Packers (NFL)",
  "Houston Rockets (NBA)",
  "Inter Milan (Serie A)",
  "Kansas City Chiefs (NFL)",
  "Liverpool FC (Premier League)",
  "Los Angeles Dodgers (MLB)",
  "Los Angeles Lakers (NBA)",
  "Los Angeles Rams (NFL)",
  "Manchester City FC (Premier League)",
  "Manchester City FC (Premier League)",
  "Manchester United FC (Premier League)",
  "Miami Dolphins (NFL)",
  "Miami Heat (NBA)",
  "Minnesota Vikings (NFL)",
  "New England Patriots (NFL)",
  "New England Patriots (NFL)",
  "New Orleans Saints (NFL)",
  "New York Giants (NFL)",
  "New York Knicks (NBA)",
  "New York Lakers (NBA)",
  "New York Mets (MLB)",
  "New York Yankees (MLB)",
  "Philadelphia Eagles (NFL)",
  "Pittsburgh Steelers (NFL)",
  "Portland Trail Blazers (NBA)",
  "Real Madrid Baloncesto (Liga ACB)",
  "Real Madrid CF (La Liga)",
  "San Antonio Spurs (NBA)",
  "San Francisco 49ers (NFL)",
  "Seattle Seahawks (NFL)",
  "Seattle Sounders FC (MLS)",
  "Tottenham Hotspur FC (Premier League)",
  "Toronto Blue Jays (MLB)",
  "Toronto Raptors (NBA)",
  "Utah Jazz (NBA)",
]
